### ISSUE TITLE
tests failing because of missing Bioregistry regular expression

### ISSUE THREAD

**Issue by egonw** [bridgedb/tiwid#22]
See https://github.com/biopragmatics/bioregistry/issues/821

**Update**: [This](https://github.com/bridgedb/tiwid/blob/main/tests/test_integrity.py#L37-L38) part of our testing code is not testing this project but is testing Bioregistry:

```python
  pattern = bioregistry.get_pattern(prefix)
  self.assertIsNotNone(pattern)
```

**Comment by cthoyt** [comment]
In my opinion, merging a PR that violates the data integrity checks is problematic. If new data does not pass the data integrity check, this is a chance for the submitter (and other stakeholders) to do two kinds of introspection:

1. Have we appropriately aligned with the external standard that is being used for data integrity testing? in this instance, the Bioregistry is the external standard for CURIE validation
2. If we haven't aligned with the external standard, why is this the case? Some possibilities are:
    - We weren't aware of the external standard
    - We don't agree with the external standard
	
In the case when we weren't aware of the external standard, we can simply align to it. In the case where we don't agree with the external standard, this is a chance to engage with the external standards body (in this case, the Bioregistry) to suggest improvements. 

However, explicitly disregarding these leads to a resource that no longer is interoperable, since there exist other data in other places that are standardized to it. In terms of the social aspects, the need to pass CI is very powerful, and leaving the main branch failing CI is IMO an implicit invitation for future changes to be less careful. My goal isn't to disparage the work that went into adding these interesting new data, but only to make more aware that it's important to align to standards.

Specifically related to the capitalization or lowercasing of identifiers in a situation where it seems the first-party website will accept either, we should consider another place where this happens: PMC. If I recall correctly, PMCs are usually uppercased. This is why the Bioregistry regex checks to uppercase for PMC. I'm perfectly happy to update the PPR record to be uppercased, but this needs to be thought through in full:

- Is there a first-party source that describes how this semantic space should be used?
- Even if a web endpoint can accept any capitalization variant, how are these displayed on the first party website?

The first party resource describing PPR is at https://europepmc.org/Preprints (thanks for the link in #21). Unfortunately, it doesn't actually give information on how to write it properly (most resources aren't so thorough that they describe *how* references should be written). After taking a look at an example suggested from the Bioregistry on https://europepmc.org/article/ppr/ppr103739, you can see that PPR is uppercased. Therefore it makes sense to update this record.

Still, I don't agree with the decision to merge #21 without solving the upstream issue first. It could have been the case that after some discussion, and reflection it could have been decided to keep the regex as is. The process for merging #21 did not seem to consider that, which worries me.

The Bioregistry has a pretty good track record of turning over issues quickly and having a nightly release cycle. Was it the case that the hasty merge of #21 was due to the fact that it would have taken some time to handle this issue? Or was is that you were sure that you were right and the Bioregistry was wrong? Maybe this can be a learning experience for all of us. My goal is to continue promoting the Bioregistry as a golden external standard to help in cases like this. I would be very sad if the Bioregistry seemed more like a hurdle to jump over than a tool and a good friend for your data. 

Anyway, thanks for indulging me. I will fix the PPR record ASAP!

**Comment by cthoyt** [comment]
Second note, it turns out that PPR didn't even have a regular expression string, so the fact that the PR was merged with tests failing could have been avoided by reading the testing logs to see the note that names of files should be lowercased. The lowercase/uppercase issue was not actually related to the CI

**Comment by egonw** [comment]
> In my opinion, merging a PR that violates the data integrity checks is problematic. If new data does not pass the data integrity check

This is the thing. I strongly feel we must not put technology above our work. The patch was correct; the test was broken (an issue was filed for that).

Of course, I could have written a fix for our test. But I think the upstream missing info (upstream was not wrong either; our test was broken: it should not conclude the data is wrong when upstream does not have a regular expression) was easily enough added.

**Comment by egonw** [comment]
> The lowercase/uppercase issue was not actually related to the CI

Actually, that's not what I observed. Our test (here too, a problem with the testing) is case sensitive and it did not recognize "PPR" as the "ppr" prefix.

**Comment by egonw** [comment]
> Or was is that you were sure that you were right and the Bioregistry was wrong?

Actually. neither. The code was and is correct. The test is failing incorrectly. That is my statement.
